spring:
  redis:
    host: 172.18.36.120
    database: 0
  datasource:
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 1
      maximum-pool-size: 5
#      pool-name: dbcp1
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.18.36.120:3306/zb?autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource


logging:
  level:
    com.su: DEBUG
#    org.springframework.security: INFO
#  file: /var/log/java/sso.log

wechat:
  appId: 12345
  appSecret: '{cipher}a68e844cb07bdc673fe1027c7541411ad8e5ddedd70a857d0d4c884833ed5c5b'